packages:
  - 'docs'
  - 'packages/*'

allowBuilds:
  esbuild: false
  sharp: false
  unrs-resolver: false

# Prevent installing packages published in the last 3 days.
minimumReleaseAge: 4320
minimumReleaseAgeExclude:
  - astro
  - '@astrojs/starlight'
  - '@astrojs/markdown-satteri'
  - 'astro-expressive-code'
  - 'rehype-expressive-code'
  - 'expressive-code'
  - '@expressive-code/*'
