name: autofix.ci

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}

jobs:
  autofix:
    name: Format code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Install pnpm, Node.js, and dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: true

      - name: Format code
        run: pnpm format

      - name: Run autofix
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        with:
          fail-fast: false
