name: release

permissions: {}

on:
  push:
    branches:
      - main

jobs:
  changeset:
    name: Changeset
    if: ${{ github.repository_owner == 'hideoo' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install pnpm, Node.js, and dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          cache: false

      - name: Create Release Pull Request or Publish
        uses: changesets/action@ae32849d5ba541f9ae29e40e22a623bc13562f51 # v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-script: pnpm run version
          publish-script: pnpm changeset publish
          commit-message: 'ci: release'
          pr-title: 'ci: release'
